### ISSUE TITLE
Not able to clone repository

### ISSUE THREAD

**Issue by ShubhamGoyal7125** [Aditya-devp/Contributershub#47]
It is showing me the following error when I try to clone the repository.
I think the issue is with the file named "..."  int the path "C++/OOPS Concepts/...".

error: invalid path 'C++/OOPS Concepts/...'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by Aditya-devp** [comment]
Hii, i've made some changes retry cloning it'll work now

**Comment by ShubhamGoyal7125** [comment]
Hi, Again there is an issue in the following path, I think it is again due to ... file.
error: invalid path 'WebD/Card-Slider/image/...'
